# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FreeRADIUS
description: > # this means to ignore newlines until "baseurl:"
  The world's leading RADIUS server. The project includes a GPL
  AAA server, BSD licensed client and PAM and Apache modules. Full
  support is available from NetworkRADIUS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "new.freeradius.org" # the base hostname & protocol for your site
#url: "localhost" # the base hostname & protocol for your site
# email: your-email@domain.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"
  - "makefile"
  - "bs-config.js"
  - "Vagrantfile"
  - "freeradius-server"

sass:
  load_paths:
    - _sass
    - bower_components/foundation-sites/scss
