#!/usr/bin/env perl

use strict;
use warnings;
use CGI();
my $html = CGI->new;


my $release = <>;
my $version = $release;
$version =~ s/^FreeRADIUS //;
$version =~ s/\s.*//;

#
#  FIXME: automatically read the changelog, and
#  create the output file.
#

my $li = 0;

while (<>) {
    last if (/^FreeRADIUS/);

    s/^\t//;
    chop;

    s/&/&amp;/g;
    s/</&lt;/g;
    s/>/&gt;/g;

    if (/^Feature improvements/i) {
	print "<h3>Feature improvements</h3>\n";
	print "<ul>\n";
	$li = 0;
	next;
    }

    if (/^Bug fixes/i) {
	print "</li>\n";
	print "</ul>\n";
	$li = 0;
	print "<h3>Bug Fixes</h3>\n";
	print "<ul>\n";
	next;
    }

    if (/^\s*$/) {
	next;
    }

    $_ = $html->escapeHTML($_);

    if (/#\d+/) {
	s,#(\d+),#<a href="https://github.com/FreeRADIUS/freeradius-server/issues/$1">$1</a>,;
    }

    if (/^\* /) {
	print "</li>\n" if ($li);

	s/^\* //;
	print "<li>", $_, "\n";
	$li = 1;
	next;
    }

    s/^  //;
    print $_, "\n";
}

print "</li>\n";
print "</ul>\n";
